// ===========================================================================
//   CART 
// ===========================================================================
/*
    TYPE
*/
export const GET_ORDERS_SUMMARY_REQUESTED = 'GET_ORDERS_SUMMARY_REQUESTED'
export const ADDED_TO_CART_REQUESTED = 'ADDED_TO_CART_REQUESTED'
export const REMOVE_TO_CART_REQUESTED = 'REMOVE_TO_CART_REQUESTED'
export const CHECKOUT_CART_REQUESTED = 'CHECKOUT_CART_REQUESTED'
export const RESERVED_BUYER_REQUESTED = 'RESERVED_BUYER_REQUESTED'
export const GET_RESERVATION_DETAILS_REQUESTED = 'GET_RESERVATION_DETAILS_REQUESTED'
export const DELETE_RESERVATION_REQUESTED = 'DELETE_RESERVATION_REQUESTED'
export const SEARCH_RESERVATION_REQUESTED = 'SEARCH_RESERVATION_REQUESTED'
export const MOVE_TO_CART_REQUESTED = 'MOVE_TO_CART_REQUESTED'

/*
    REDUCER
*/
export const ADDED_TO_CART = 'ADDED_TO_CART'
export const RETRIEVED_ORDERS_SUMMARY = 'RETRIEVED_ORDERS_SUMMARY'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const CHECKOUT_CART = 'CHECKOUT_CART'
export const RESET_CART = 'RESET_CART'
export const RESERVED_BUYER = 'RESERVED_BUYER'
export const RETRIEVED_RESERVATION_DETAILS = 'RETRIEVED_RESERVATION_DETAILS'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'




