// USER
export const ERROR_LOGGING_USER = 'ERROR_LOGGING_USER'

//SELLER
export const ERROR_CREATING_SELLER = 'ERROR_CREATING_SELLER'
export const ERROR_VERIFYING_EMAIL = 'ERROR_VERIFYING_EMAIL'
export const ERROR_CHECK_EMAIL_TOKEN = 'ERROR_CHECK_EMAIL_TOKEN' 

//BUYER
export const ERROR_CREATING_BUYER = 'ERROR_CREATING_BUYER'


//PRODUCT
export const ERROR_CREATING_PRODUCT = 'ERROR_CREATING_PRODUCT'
export const ERROR_GETTING_PRODUCTS = 'ERROR_GETTING_PRODUCTS'
export const ERROR_GETTING_PRODUCT_DETAILS = 'ERROR_GETTING_PRODUCT_DETAILS'
export const ERROR_GETTING_ALL_SELLERS_PRODUCTS = 'ERROR_GETTING_ALL_SELLERS_PRODUCTS'

