// ===========================================================================
//   PRODUCT 
// ===========================================================================
/*
    TYPE
*/
export const CREATE_PRODUCT_REQUESTED = 'CREATE_PRODUCT_REQUESTED'
export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED'
export const GET_PRODUCT_DETAILS_REQUESTED = 'GET_PRODUCT_DETAILS_REQUESTED'
export const GET_ALL_SELLERS_PRODUCT_REQUESTED = 'GET_ALL_SELLERS_PRODUCT_REQUESTED'
export const UPDATE_PRODUCT_REQUESTED = 'UPDATE_PRODUCT_REQUESTED'
export const DEACTIVATE_PRODUCT_REQUESTED = 'DEACTIVATE_PRODUCT_REQUESTED'
export const ACTIVATE_PRODUCT_REQUESTED = 'ACTIVATE_PRODUCT_REQUESTED'
export const GET_DEACTIVATED_PRODUCTS_REQUESTED = 'GET_DEACTIVATED_PRODUCTS_REQUESTED'
export const FILTER_BY_PLACES_REQUESTED = 'FILTER_BY_PLACES_REQUESTED'
export const SEARCH_PRODUCT_BY_NAME_REQUESTED = 'SEARCH_PRODUCT_BY_NAME_REQUESTED'
export const GET_ALL_COMMENTS_BY_PRODUCT_REQUESTED = 'GET_ALL_COMMENTS_BY_PRODUCT_REQUESTED'
export const GIVE_FEEDBACK_RATE_REQUESTED = 'GIVE_FEEDBACK_RATE_REQUESTED'
export const CHECK_IF_BUYER_ORDERED_REQUESTED = 'CHECK_IF_BUYER_ORDERED_REQUESTED'
export const GET_ALL_REVIEWS_OF_PRODUCT_REQUESTED = 'GET_ALL_REVIEWS_OF_PRODUCT_REQUESTED'
export const LISTS_OF_SELLERS_REQUESTED = 'LISTS_OF_SELLERS_REQUESTED'

/*
    REDUCER
*/
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const RETRIEVED_PRODUCT = 'RETRIEVED_PRODUCT'
export const RETRIEVED_PRODUCT_DETAILS = 'RETRIEVED_PRODUCT_DETAILS'
export const SHOW_PRODUCT_DETAILS = 'SHOW_PRODUCT_DETAILS'
export const RETRIEVED_ALL_SELLERS_PRODUCTS = 'RETRIEVED_ALL_SELLERS_PRODUCTS'
export const ORDER_QUANTITY_INCREMENT = 'ORDER_QUANTITY_INCREMENT'
export const ORDER_QUANTITY_DECREMENT = 'ORDER_QUANTITY_DECREMENT'
export const CLEAR_CART_QUANTITY =  'CLEAR_CART_QUANTITY'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const CLEAR_STATE = 'CLEAR_STATE'
export const DEACTIVATED_PRODUCT = 'DEACTIVATED_PRODUCT'
export const ACTIVATED_PRODUCT = 'ACTIVATED_PRODUCT'
export const RETRIEVED_DEACTIVATED_PRODUCTS = 'RETRIEVED_DEACTIVATED_PRODUCTS'
export const FILTER_SELLERS_PRODUCTS = 'FILTER_SELLERS_PRODUCTS'
export const FILTER_BY_PLACES = 'FILTER_BY_PLACES'
export const SEARCH_PRODUCT_BY_NAME = 'SEARCH_PRODUCT_BY_NAME'
export const RETRIEVED_ALL_COMMENTS_BY_PRODUCT = 'RETRIEVED_ALL_COMMENTS_BY_PRODUCT'
export const GIVE_FEEDBACK = 'GIVE_FEEDBACK'
export const CHECK_IF_BUYER_ORDERED = 'CHECK_IF_BUYER_ORDERED'
export const RETRIEVED_ALL_REVIEWS_OF_PRODUCT = 'RETRIEVED_ALL_REVIEWS_OF_PRODUCT'
export const CLEAR_PRODUCTS_IF_LOGOUT = 'CLEAR_PRODUCTS_IF_LOGOUT'
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS'
export const LISTS_OF_SELLERS = 'LISTS_OF_SELLERS'





