// ===========================================================================
// SELLER 
// ===========================================================================
/*
    TYPE
*/

export const VERIFY_EMAIL_REQUESTED = 'VERIFY_EMAIL_REQUESTED'
export const CREATE_SELLER_REQUESTED = 'CREATE_SELLER_REQUESTED'
export const CHECK_EMAIL_TOKEN_REQUESTED = 'CHECK_EMAIL_TOKEN_REQUESTED'
export const CHECK_CODE_EXIST_REQUESTED = 'CHECK_CODE_EXIST_REQUESTED'
export const GET_UNVERIFIED_SELLERS_REQUESTED = 'GET_UNVERIFIED_SELLERS_REQUESTED'
export const VERIFY_SELLER_REQUESTED = 'VERIFY_SELLER_REQUESTED'
export const GET_SELLER_INVENTORY_REPORT_REQUESTED = 'GET_SELLER_INVENTORY_REPORT_REQUESTED'
export const SEARCH_PRODUCT_NAME_REQUESTED = 'SEARCH_PRODUCT_NAME_REQUESTED'
export const GET_ALL_SELLERS_REQUESTED = 'GET_ALL_SELLERS_REQUESTED'
export const GET_ORDERS_OF_BUYERS_REQUESTED = 'GET_ORDERS_OF_BUYERS_REQUESTED'
export const DEACTIVATE_SELLER_REQUESTED = 'DEACTIVATE_SELLER_REQUESTED'
export const ACTIVATE_SELLER_REQUESTED = 'ACTIVATE_SELLER_REQUESTED'
export const GET_COINS_PH_PAYMENT_REQUESTED = 'GET_COINS_PH_PAYMENT_REQUESTED'
export const UPDATE_SELLER_TOKEN_REQUESTED = 'UPDATE_SELLER_TOKEN_REQUESTED'
export const SEARCH_PAID_UNPAID_SELLER_REQUESTED = 'SEARCH_PAID_UNPAID_SELLER_REQUESTED'

/*
    REDUCER
*/
export const CREATE_SELLER = 'CREATE_SELLER'
export const CLEAR_SELLER_STATE = 'CLEAR_SELLER_STATE'
export const SENT_EMAIL = 'SENT_EMAIL'
export const CHECK_EMAIL_TOKEN = 'CHECK_EMAIL_TOKEN'
export const CHECK_CODE_EXISTS = 'CHECK_CODE_EXISTS'
export const CODE_NOT_EXIST = 'CODE_NOT_EXIST'
export const RETRIEVED_UNVERIFIED_SELLERS = 'RETRIEVED_UNVERIFIED_SELLERS'
export const VERIFY_SELLER = 'VERIFY_SELLER'
export const CLEAR_TOAST = 'CLEAR_TOAST'
export const RETRIEVED_SELLER_INVENTORY_REPORT = 'RETRIEVED_SELLER_INVENTORY_REPORT'
export const SEARCH_PRODUCT_NAME = 'SEARCH_PRODUCT_NAME'
export const RETRIEVE_ALL_SELLERS = 'RETRIEVE_ALL_SELLERS'
export const RETRIEVE_ORDERS_OF_BUYERS = 'RETRIEVE_ORDERS_OF_BUYERS'
export const DEACTIVATE_SELLER = 'DEACTIVATE_SELLER'
export const ACTIVATE_SELLER = 'ACTIVATE_SELLER'
export const RETRIEVED_COINS_PH_PAYMENT = 'RETRIEVED_COINS_PH_PAYMENT'
export const UPDATED_SELLER_TOKEN = 'UPDATED_SELLER_TOKEN'
export const SEARCH_PAID_UNPAID_SELLER = 'SEARCH_PAID_UNPAID_SELLER'
export const CLEAR_SELLER_UNMOUNT = 'CLEAR_SELLER_UNMOUNT'








