// ===========================================================================
// SELLER 
// ===========================================================================
/*
    TYPE
*/

export const VERIFY_EMAIL_REQUESTED = 'VERIFY_EMAIL_REQUESTED'
export const CREATE_SELLER_REQUESTED = 'CREATE_SELLER_REQUESTED'
export const CHECK_EMAIL_TOKEN_REQUESTED = 'CHECK_EMAIL_TOKEN_REQUESTED'
export const CHECK_CODE_EXIST_REQUESTED = 'CHECK_CODE_EXIST_REQUESTED'
export const GET_UNVERIFIED_SELLERS_REQUESTED = 'GET_UNVERIFIED_SELLERS_REQUESTED'
export const VERIFY_SELLER_REQUESTED = 'VERIFY_SELLER_REQUESTED'
export const GET_SELLER_INVENTORY_REPORT_REQUESTED = 'GET_SELLER_INVENTORY_REPORT_REQUESTED'
export const SEARCH_PRODUCT_NAME_REQUESTED = 'SEARCH_PRODUCT_NAME_REQUESTED'
export const GET_ALL_SELLERS_REQUESTED = 'GET_ALL_SELLERS_REQUESTED'
export const GET_ORDERS_OF_BUYERS_REQUESTED = 'GET_ORDERS_OF_BUYERS_REQUESTED'
export const DEACTIVATE_SELLER_REQUESTED = 'DEACTIVATE_SELLER_REQUESTED'
export const ACTIVATE_SELLER_REQUESTED = 'ACTIVATE_SELLER_REQUESTED'
export const GET_COINS_PH_PAYMENT_REQUESTED = 'GET_COINS_PH_PAYMENT_REQUESTED'
export const UPDATE_SELLER_TOKEN_REQUESTED = 'UPDATE_SELLER_TOKEN_REQUESTED'
export const SEARCH_PAID_UNPAID_SELLER_REQUESTED = 'SEARCH_PAID_UNPAID_SELLER_REQUESTED'
export const UPDATE_BUYER_STATUS_WHEN_ORDER_PAID_REQUESTED = 'UPDATE_BUYER_STATUS_WHEN_ORDER_PAID_REQUESTED'
export const GET_DELIVERY_DETAILS_REQUESTED = 'GET_DELIVERY_DETAILS_REQUESTED'
export const GET_SELLER_DETAILS_REQUESTED = 'GET_SELLER_DETAILS_REQUESTED'
export const UPDATE_SELLER_DETAILS_REQUESTED = 'UPDATE_SELLER_DETAILS_REQUESTED'
export const GET_BUYERS_ORDERED_BY_PRODUCT_REQUESTED = 'GET_BUYERS_ORDERED_BY_PRODUCT_REQUESTED'
export const GET_ALL_SELLERS_WHO_PAID_REQUESTED = 'GET_ALL_SELLERS_WHO_PAID_REQUESTED'
export const GET_BUYERS_NOTICATION_REQUESTED = 'GET_BUYERS_NOTICATION_REQUESTED'
export const UPDATE_NOTIFICATION_STATUS_REQUESTED = 'UPDATE_NOTIFICATION_STATUS_REQUESTED'
export const SEARCH_ORDERS_REQUESTED = 'SEARCH_ORDERS_REQUESTED'
export const GET_RESERVATION_TAB_DETAILS_REQUESTED = 'GET_RESERVATION_TAB_DETAILS_REQUESTED'
export const SEARCH_RESERVATION_TAB_DETAILS_REQUESTED = 'SEARCH_RESERVATION_TAB_DETAILS_REQUESTED'
export const UPDATE_PENDING_DELIVERY_REQUESTED = 'UPDATE_PENDING_DELIVERY_REQUESTED'
export const GOOGLE_PLACE_REQUESTED = 'GOOGLE_PLACE_REQUESTED'

/*
    REDUCER
*/
export const CREATE_SELLER = 'CREATE_SELLER'
export const CLEAR_SELLER_STATE = 'CLEAR_SELLER_STATE'
export const SENT_EMAIL = 'SENT_EMAIL'
export const CHECK_EMAIL_TOKEN = 'CHECK_EMAIL_TOKEN'
export const CHECK_CODE_EXISTS = 'CHECK_CODE_EXISTS'
export const CODE_NOT_EXIST = 'CODE_NOT_EXIST'
export const RETRIEVED_UNVERIFIED_SELLERS = 'RETRIEVED_UNVERIFIED_SELLERS'
export const VERIFY_SELLER = 'VERIFY_SELLER'
export const CLEAR_TOAST = 'CLEAR_TOAST'
export const RETRIEVED_SELLER_INVENTORY_REPORT = 'RETRIEVED_SELLER_INVENTORY_REPORT'
export const SEARCH_PRODUCT_NAME = 'SEARCH_PRODUCT_NAME'
export const RETRIEVE_ALL_SELLERS = 'RETRIEVE_ALL_SELLERS'
export const RETRIEVE_ORDERS_OF_BUYERS = 'RETRIEVE_ORDERS_OF_BUYERS'
export const DEACTIVATE_SELLER = 'DEACTIVATE_SELLER'
export const ACTIVATE_SELLER = 'ACTIVATE_SELLER'
export const RETRIEVED_COINS_PH_PAYMENT = 'RETRIEVED_COINS_PH_PAYMENT'
export const UPDATED_SELLER_TOKEN = 'UPDATED_SELLER_TOKEN'
export const SEARCH_PAID_UNPAID_SELLER = 'SEARCH_PAID_UNPAID_SELLER'
export const CLEAR_SELLER_UNMOUNT = 'CLEAR_SELLER_UNMOUNT'
export const CLEAR_STATUS = 'CLEAR_STATUS'
export const RETRIEVED_DELIVERY_DETAILS = 'RETRIEVED_DELIVERY_DETAILS'
export const UPDATE_SELLER_ACCOUNT = 'UPDATE_SELLER_ACCOUNT'
export const CLOSE_UPDATE_SELLER_ACCOUNT = 'CLOSE_UPDATE_SELLER_ACCOUNT'
export const RETRIEVED_SELLER_DETAILS = 'RETRIEVED_SELLER_DETAILS'
export const UPDATE_SELLER_DETAILS = 'UPDATE_SELLER_DETAILS'
export const RETRIEVED_BUYERS_ORDERED_BY_PRODUCT = 'RETRIEVED_BUYERS_ORDERED_BY_PRODUCT'
export const RETRIEVED_ALL_SELLERS_WHO_PAID = 'RETRIEVED_ALL_SELLERS_WHO_PAID'
export const OPEN_ORDERS_NOTIFICATION = 'OPEN_ORDERS_NOTIFICATION'
export const RESET_ACTIVE_INDEX = 'RESET_ACTIVE_INDEX'
export const RETRIEVED_BUYERS_NOTICATION = 'RETRIEVED_BUYERS_NOTICATION'
export const RETRIEVED_RESERVATION_TAB_DETAILS = 'RETRIEVED_RESERVATION_TAB_DETAILS'
export const RETRIEVED_ORDERS_OF_BUYERS_TWO = 'RETRIEVED_ORDERS_OF_BUYERS_TWO'
export const UPDATED_PENDING_DELIVERY = 'UPDATE_PENDING_DELIVERY'
export const CLEAR_DELIVERY_STATUS = 'CLEAR_DELIVERY_STATUS'
export const GOOGLE_PLACE = 'GOOGLE_PLACE'
export const CLEAR_GOOGLE_PLACE = 'CLEAR_GOOGLE_PLACE'













